Repository floatme-corp/golflog, pull requests merged in 2022-03, with the labels that each got.

#5 chore(doc): add highlighting to README.md
  README.md
Labels: ignore-for-release

#8 fix(mod): add stub for mock package
  Makefile
  mocks/stub.go
Labels: fix

#11 feat(log): add Error helper
  README.md
  go.mod
  go.sum
  log.go
  log_test.go
Labels: feature

#12 feat(context): add `ContextWithNameAndValues` helper
  README.md
  context.go
  context_test.go
Labels: feature

#15 feat(log): add helpers
  README.md
  context_test.go
  log.go
  log_test.go
Labels: feature

#21 feat(log): add `logr.Discard` proxy
  log.go
Labels: feature

#22 chore(actions): rename commits.yml -> commits.yaml
  .github/workflows/commits.yaml
Labels: ignore-for-release

#24 fix(make): use tabs for make indentation
  Makefile
Labels: fix
