Repository floatme-corp/golflog, pull requests merged in 2022-04, with the labels that each got.

#27 chore(tools): use coveralls
  .github/workflows/coverage.yaml
  .github/workflows/test.yaml
  Dockerfile.devkit
  Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: ignore-for-release

#37 fix(devkit): set safe directory
  Makefile
Labels: fix

#35 feat(log): add `WarnWrap` helper
  README.md
  go.sum
  log.go
  log_test.go
Labels: feature

#39 chore(actions): use service account for release-please
  .github/workflows/release-main.yaml
Labels: ignore-for-release
